/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author angul
 */
import negocio.ArticuloNegocio;
import java.util.Map;
import modelo.Articulo;
public class EstadisticaPanel extends javax.swing.JPanel {
    private ArticuloNegocio articuloNegocio;
    private ArticuloPanel articuloPanel;
    private EstadisticaPanel estadisticaPanel;
    

    /**
     * Creates new form Estadistica
     */
    public EstadisticaPanel(ArticuloNegocio articuloNegocio) {
        initComponents();
        this.articuloNegocio = articuloNegocio;
        txtEstadisticas.setEditable(false);
    txtEstadisticas.setFocusable(false);
        actualizarEstadisticas();
    }
    
    public void actualizarEstadisticas() {

        StringBuilder texto = new StringBuilder();

        texto.append("ESTADÍSTICAS DEL INVENTARIO\n\n");

        texto.append("Total de artículos: ")
                .append(articuloNegocio.totalArticulos()).append("\n");

        texto.append("Artículos disponibles: ")
                .append(articuloNegocio.articulosDisponibles()).append("\n");

       

        texto.append("Unidades almacenadas: ")
                .append(articuloNegocio.unidadesAlmacenadas()).append("\n");

        Articulo mayor = articuloNegocio.articuloMayorPrecio();
        Articulo menor = articuloNegocio.articuloMenorPrecio();

        texto.append("Artículo con mayor precio: ")
                .append(mayor != null ? mayor.getTitulo() : "Ninguno").append("\n");

        texto.append("Artículo con menor precio: ")
                .append(menor != null ? menor.getTitulo() : "Ninguno").append("\n");

        texto.append("Valor total del inventario: ₡")
                .append(articuloNegocio.valorTotalInventario()).append("\n\n");

        texto.append("Artículos por categoría:\n");

        for (Map.Entry<String, Integer> entrada : articuloNegocio.articulosPorCategoria().entrySet()) {
            texto.append("- ")
                    .append(entrada.getKey())
                    .append(": ")
                    .append(entrada.getValue())
                    .append("\n");
        }

        txtEstadisticas.setText(texto.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEstadisticas = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(txtEstadisticas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtEstadisticas;
    // End of variables declaration//GEN-END:variables
}
